### ISSUE TITLE
url crate version

### ISSUE THREAD

**Issue by scturtle** [wezm/feedfinder#7]
Please consider upgrade url crate's version to 2.* or re-export the current version's `Url`?

**Comment by wezm** [comment]
It looks like I could change the `url` version requirement to `url = ">= 1, < 3"` and have it support 1 and 2.

Just to confifrm, is there reason you're after this to avoid having two versions of `url` in your dependency tree.

**Comment by scturtle** [comment]
Actually I'm only using `url` with this crate. So it would be helpful if you could re-export `url` crate or `Url` struct like [this one](https://github.com/sagebind/isahc/blob/master/src/lib.rs#L253-L254). In this way I do not need to add `url` as a dependency and specify a version.

And thanks for this crate! It works out of box.

**Comment by wezm** [comment]
Ahh thanks for the clarification, that's helpful. I'll aim to make that change tonight.

**Comment by wezm** [comment]
I've published 0.3, which re-exports url::Url.
